# Site settings
title: CoderDojoChi
description: Welcome to CoderDojoChi’s GitHub page. We use GitHub pages extensively for our slides, cheatsheets, and teaching tools.
baseurl: ""
url: "http://coderdojochi.com"
author: "CoderDojoChi <info@coderdojochi.org>"
email: info@coderdojochi.org
twitter_username: CoderDojoChi
github_username:  CoderDojoChi
facebook_username: CoderDojoChi

# Build settings
gems:
  - jekyll-redirect-from

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

include:
  - _pages

sass:
  style: compressed
