# Site settings
title: CoderDojoChi GitHub
tag_text: Solo
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: info@coderdojochi.org
twitter_username: CoderDojoChi
github_username:  CoderDojoChi
facebook_username: CoderDojoChi

# Build settings
gems:
  - jekyll-redirect-from
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
sass:
  style: compressed

